export interface Country {
  fullName: string;
  commonName: string;
  countryCode: string;
}

export function countryCodeFromMID (mid: string) : string {
  return midCountryCodes[mid];
}

export function countryFromCountryCode (code: string) : Country {
  return countryCodes[code];
}

export function countryFromMid (mid: string): Country {
  return countryFromCountryCode(countryCodeFromMID(mid));
}

/*

  QUESTIONS NEXT
  - Is MMSICountry really the best name here? Should it just be Country or similar?

*/

const countryCodes: { [code: string]: Country } = {
  "AD": { commonName: "Andorra", fullName: "Andorra (Principality of)", countryCode: "AD" },
  "AE": { commonName: "United Arab Emirates", fullName: "United Arab Emirates", countryCode: "AE" },
  "AF": { commonName: "Afghanistan", fullName: "Afghanistan", countryCode: "AF" },
  "AG": { commonName: "Antigua and Barbuda", fullName: "Antigua and Barbuda", countryCode: "AG" },
  "AI": { commonName: "Anguilla", fullName: "Anguilla", countryCode: "AI" },
  "AL": { commonName: "Albania", fullName: "Albania (Republic of)", countryCode: "AL" },
  "AM": { commonName: "Armenia", fullName: "Armenia (Republic of)", countryCode: "AM" },
  "AO": { commonName: "Angola", fullName: "Angola (Republic of)", countryCode: "AO" },
  "AR": { commonName: "Argentine Republic", fullName: "Argentine Republic", countryCode: "AR" },
  "AS": { commonName: "American Samoa", fullName: "American Samoa", countryCode: "AS" },
  "AT": { commonName: "Austria", fullName: "Austria", countryCode: "AT" },
  "AU": { commonName: "Australia", fullName: "Australia", countryCode: "AU" },
  "AW": { commonName: "Aruba", fullName: "Aruba", countryCode: "AW" },
  "AZ": { commonName: "Azerbaijan", fullName: "Azerbaijani Republic", countryCode: "AZ" },
  "BA": { commonName: "Bosnia and Herzegovina", fullName: "Bosnia and Herzegovina", countryCode: "BA" },
  "BB": { commonName: "Barbados", fullName: "Barbados", countryCode: "BB" },
  "BD": { commonName: "Bangladesh", fullName: "Bangladesh (People's Republic of)", countryCode: "BD" },
  "BE": { commonName: "Belgium", fullName: "Belgium", countryCode: "BE" },
  "BF": { commonName: "Burkina Faso", fullName: "Burkina Faso", countryCode: "BF" },
  "BG": { commonName: "Bulgaria", fullName: "Bulgaria (Republic of)", countryCode: "BG" },
  "BH": { commonName: "Bahrain", fullName: "Bahrain (Kingdom of)", countryCode: "BH" },
  "BI": { commonName: "Burundi", fullName: "Burundi (Republic of)", countryCode: "BI" },
  "BJ": { commonName: "Benin", fullName: "Benin (Republic of)", countryCode: "BJ" },
  "BM": { commonName: "Bermuda", fullName: "Bermuda", countryCode: "BM" },
  "BN": { commonName: "Brunei Darussalam", fullName: "Brunei Darussalam", countryCode: "BN" },
  "BO": { commonName: "Bolivia", fullName: "Bolivia (Republic of)", countryCode: "BO" },
  "BQ,CW,SX": {
    commonName: "Caribbean Netherlands; Curaçao; Sint Maarten",
    fullName: "Bonaire, Sint Eustatius and Saba; Curaçao; Sint Maarten - Netherlands (Kingdom of the)",
    countryCode: "BQ,CW,SX",
  },
  "BR": { commonName: "Brazil", fullName: "Brazil (Federative Republic of)", countryCode: "BR" },
  "BS": { commonName: "Bahamas", fullName: "Bahamas (Commonwealth of the)", countryCode: "BS" },
  "BT": { commonName: "Bhutan", fullName: "Bhutan (Kingdom of)", countryCode: "BT" },
  "BW": { commonName: "Botswana", fullName: "Botswana (Republic of)", countryCode: "BW" },
  "BY": { commonName: "Belarus", fullName: "Belarus (Republic of)", countryCode: "BY" },
  "BZ": { commonName: "Belize", fullName: "Belize", countryCode: "BZ" },
  "CA": { commonName: "Canada", fullName: "Canada", countryCode: "CA" },
  "CC": { commonName: "Cocos", fullName: "Cocos (Keeling) Islands", countryCode: "CC" },
  "CD": { commonName: "Democratic Republic of the Congo", fullName: "Democratic Republic of the Congo", countryCode: "CD" },
  "CF": { commonName: "Central African Republic", fullName: "Central African Republic", countryCode: "CF" },
  "CG": { commonName: "Congo", fullName: "Congo (Republic of the)", countryCode: "CG" },
  "CH": { commonName: "Switzerland", fullName: "Switzerland (Confederation of)", countryCode: "CH" },
  "CI": { commonName: "Côte d'Ivoire", fullName: "Côte d'Ivoire (Republic of)", countryCode: "CI" },
  "CK": { commonName: "Cook Islands", fullName: "Cook Islands", countryCode: "CK" },
  "CL": { commonName: "Chile", fullName: "Chile", countryCode: "CL" },
  "CM": { commonName: "Cameroon", fullName: "Cameroon (Republic of)", countryCode: "CM" },
  "CN": { commonName: "China", fullName: "China (People's Republic of)", countryCode: "CN" },
  "CO": { commonName: "Colombia", fullName: "Colombia (Republic of)", countryCode: "CO" },
  "CR": { commonName: "Costa Rica", fullName: "Costa Rica", countryCode: "CR" },
  "CU": { commonName: "Cuba", fullName: "Cuba", countryCode: "CU" },
  "CV": { commonName: "Cape Verde", fullName: "Cape Verde (Republic of)", countryCode: "CV" },
  "CX": { commonName: "Christmas Island", fullName: "Christmas Island (Indian Ocean)", countryCode: "CX" },
  "CY": { commonName: "Cyprus", fullName: "Cyprus (Republic of)", countryCode: "CY" },
  "CZ": { commonName: "Czech Republic", fullName: "Czech Republic", countryCode: "CZ" },
  "DE": { commonName: "Germany", fullName: "Germany (Federal Republic of)", countryCode: "DE" },
  "DJ": { commonName: "Djibouti", fullName: "Djibouti (Republic of)", countryCode: "DJ" },
  "DK": { commonName: "Denmark", fullName: "Denmark", countryCode: "DK" },
  "DM": { commonName: "Dominica", fullName: "Dominica (Commonwealth of)", countryCode: "DM" },
  "DO": { commonName: "Dominican Republic", fullName: "Dominican Republic", countryCode: "DO" },
  "DZ": { commonName: "Algeria", fullName: "Algeria (People's Democratic Republic of)", countryCode: "DZ" },
  "EC": { commonName: "Ecuador", fullName: "Ecuador", countryCode: "EC" },
  "EE": { commonName: "Estonia", fullName: "Estonia (Republic of)", countryCode: "EE" },
  "EG": { commonName: "Egypt", fullName: "Egypt (Arab Republic of)", countryCode: "EG" },
  "ER": { commonName: "Eritrea", fullName: "Eritrea", countryCode: "ER" },
  "ES": { commonName: "Spain", fullName: "Spain", countryCode: "ES" },
  "ET": { commonName: "Ethiopia", fullName: "Ethiopia (Federal Democratic Republic of)", countryCode: "ET" },
  "FI": { commonName: "Finland", fullName: "Finland", countryCode: "FI" },
  "FJ": { commonName: "Fiji", fullName: "Fiji (Republic of)", countryCode: "FJ" },
  "FK": { commonName: "Falkland Islands", fullName: "Falkland Islands (Malvinas)", countryCode: "FK" },
  "FM": { commonName: "Micronesia", fullName: "Micronesia (Federated States of)", countryCode: "FM" },
  "FO": { commonName: "Faroe Islands", fullName: "Faroe Islands", countryCode: "FO" },
  "FR": { commonName: "France", fullName: "France", countryCode: "FR" },
  "GA": { commonName: "Gabonese Republic", fullName: "Gabonese Republic", countryCode: "GA" },
  "GB": { commonName: "United Kingdom", fullName: "United Kingdom of Great Britain and Northern Ireland", countryCode: "GB" },
  "GD": { commonName: "Grenada", fullName: "Grenada", countryCode: "GD" },
  "GE": { commonName: "Georgia", fullName: "Georgia", countryCode: "GE" },
  "GF": { commonName: "Guiana", fullName: "Guiana (French Department of)", countryCode: "GF" },
  "GH": { commonName: "Ghana", fullName: "Ghana", countryCode: "GH" },
  "GI": { commonName: "Gibraltar", fullName: "Gibraltar", countryCode: "GI" },
  "GL": { commonName: "Greenland", fullName: "Greenland", countryCode: "GL" },
  "GM": { commonName: "Gambia", fullName: "Gambia (Republic of the)", countryCode: "GM" },
  "GN": { commonName: "Guinea", fullName: "Guinea (Republic of)", countryCode: "GN" },
  "GP": { commonName: "Guadeloupe", fullName: "Guadeloupe (French Department of)", countryCode: "GP" },
  "GQ": { commonName: "Equatorial Guinea", fullName: "Equatorial Guinea (Republic of)", countryCode: "GQ" },
  "GR": { commonName: "Greece", fullName: "Greece", countryCode: "GR" },
  "GT": { commonName: "Guatemala", fullName: "Guatemala (Republic of)", countryCode: "GT" },
  "GW": { commonName: "Guinea-Bissau", fullName: "Guinea-Bissau (Republic of)", countryCode: "GW" },
  "GY": { commonName: "Guyana", fullName: "Guyana", countryCode: "GY" },
  "HK": { commonName: "Hong Kong", fullName: "Hong Kong (Special Administrative Region of China)", countryCode: "HK" },
  "HN": { commonName: "Honduras", fullName: "Honduras (Republic of)", countryCode: "HN" },
  "HR": { commonName: "Croatia", fullName: "Croatia (Republic of)", countryCode: "HR" },
  "HT": { commonName: "Haiti", fullName: "Haiti (Republic of)", countryCode: "HT" },
  "HU": { commonName: "Hungary", fullName: "Hungary (Republic of)", countryCode: "HU" },
  "ID": { commonName: "Indonesia", fullName: "Indonesia (Republic of)", countryCode: "ID" },
  "IE": { commonName: "Ireland", fullName: "Ireland", countryCode: "IE" },
  "IL": { commonName: "Israel", fullName: "Israel (State of)", countryCode: "IL" },
  "IN": { commonName: "India", fullName: "India (Republic of)", countryCode: "IN" },
  "IQ": { commonName: "Iraq", fullName: "Iraq (Republic of)", countryCode: "IQ" },
  "IR": { commonName: "Iran", fullName: "Iran (Islamic Republic of)", countryCode: "IR" },
  "IS": { commonName: "Iceland", fullName: "Iceland", countryCode: "IS" },
  "IT": { commonName: "Italy", fullName: "Italy", countryCode: "IT" },
  "JM": { commonName: "Jamaica", fullName: "Jamaica", countryCode: "JM" },
  "JO": { commonName: "Jordan", fullName: "Jordan (Hashemite Kingdom of)", countryCode: "JO" },
  "JP": { commonName: "Japan", fullName: "Japan", countryCode: "JP" },
  "KE": { commonName: "Kenya", fullName: "Kenya (Republic of)", countryCode: "KE" },
  "KG": { commonName: "Kyrgyzstan", fullName: "Kyrgyzstan", countryCode: "KG" },
  "KH": { commonName: "Cambodia", fullName: "Cambodia (Kingdom of)", countryCode: "KH" },
  "KI": { commonName: "Kiribati", fullName: "Kiribati (Republic of)", countryCode: "KI" },
  "KM": { commonName: "Comoros", fullName: "Comoros (Union of the)", countryCode: "KM" },
  "KN": { commonName: "Saint Kitts and Nevis", fullName: "Saint Kitts and Nevis", countryCode: "KN" },
  "KP": { commonName: "North Korea", fullName: "North Korea", countryCode: "KP" },
  "KR": { commonName: "Korea", fullName: "Korea (Republic of)", countryCode: "KR" },
  "KW": { commonName: "Kuwait", fullName: "Kuwait (State of)", countryCode: "KW" },
  "KY": { commonName: "Cayman Islands", fullName: "Cayman Islands", countryCode: "KY" },
  "KZ": { commonName: "Kazakhstan", fullName: "Kazakhstan (Republic of)", countryCode: "KZ" },
  "LA": { commonName: "Laos", fullName: "Lao People's Democratic Republic (Laos)", countryCode: "LA" },
  "LB": { commonName: "Lebanon", fullName: "Lebanon", countryCode: "LB" },
  "LC": { commonName: "Saint Lucia", fullName: "Saint Lucia", countryCode: "LC" },
  "LI": { commonName: "Liechtenstein", fullName: "Liechtenstein (Principality of)", countryCode: "LI" },
  "LK": { commonName: "Sri Lanka", fullName: "Sri Lanka (Democratic Socialist Republic of)", countryCode: "LK" },
  "LR": { commonName: "Liberia", fullName: "Liberia (Republic of)", countryCode: "LR" },
  "LS": { commonName: "Lesotho", fullName: "Lesotho (Kingdom of)", countryCode: "LS" },
  "LT": { commonName: "Lithuania", fullName: "Lithuania (Republic of)", countryCode: "LT" },
  "LU": { commonName: "Luxembourg", fullName: "Luxembourg", countryCode: "LU" },
  "LV": { commonName: "Latvia", fullName: "Latvia (Republic of)", countryCode: "LV" },
  "LY": { commonName: "Libya", fullName: "Libya", countryCode: "LY" },
  "MA": { commonName: "Morocco", fullName: "Morocco (Kingdom of)", countryCode: "MA" },
  "MC": { commonName: "Monaco", fullName: "Monaco (Principality of)", countryCode: "MC" },
  "MD": { commonName: "Moldova", fullName: "Moldova (Republic of)", countryCode: "MD" },
  "ME": { commonName: "Montenegro", fullName: "Montenegro (Republic of)", countryCode: "ME" },
  "MG": { commonName: "Madagascar", fullName: "Madagascar (Republic of)", countryCode: "MG" },
  "MH": { commonName: "Marshall Islands", fullName: "Marshall Islands (Republic of the)", countryCode: "MH" },
  "MK": { commonName: "Macedonia", fullName: "Macedonia", countryCode: "MK" },
  "ML": { commonName: "Mali", fullName: "Mali (Republic of)", countryCode: "ML" },
  "MM": { commonName: "Myanmar", fullName: "Myanmar (Union of)", countryCode: "MM" },
  "MN": { commonName: "Mongolia", fullName: "Mongolia", countryCode: "MN" },
  "MO": { commonName: "Macao", fullName: "Macao", countryCode: "MO" },
  "MP": { commonName: "Northern Mariana Islands", fullName: "Northern Mariana Islands (Commonwealth of the)", countryCode: "MP" },
  "MQ": { commonName: "Martinique", fullName: "Martinique (French Department of)", countryCode: "MQ" },
  "MR": { commonName: "Mauritania", fullName: "Mauritania (Islamic Republic of)", countryCode: "MR" },
  "MS": { commonName: "Montserrat", fullName: "Montserrat", countryCode: "MS" },
  "MT": { commonName: "Malta", fullName: "Malta", countryCode: "MT" },
  "MU": { commonName: "Mauritius", fullName: "Mauritius (Republic of)", countryCode: "MU" },
  "MV": { commonName: "Maldives", fullName: "Maldives (Republic of)", countryCode: "MV" },
  "MW": { commonName: "Malawi", fullName: "Malawi", countryCode: "MW" },
  "MX": { commonName: "Mexico", fullName: "Mexico", countryCode: "MX" },
  "MY": { commonName: "Malaysia", fullName: "Malaysia", countryCode: "MY" },
  "MZ": { commonName: "Mozambique", fullName: "Mozambique (Republic of)", countryCode: "MZ" },
  "NA": { commonName: "Namibia", fullName: "Namibia (Republic of)", countryCode: "NA" },
  "NC": { commonName: "New Caledonia", fullName: "New Caledonia", countryCode: "NC" },
  "NE": { commonName: "Niger", fullName: "Niger (Republic of the)", countryCode: "NE" },
  "NG": { commonName: "Nigeria", fullName: "Nigeria (Federal Republic of)", countryCode: "NG" },
  "NI": { commonName: "Nicaragua", fullName: "Nicaragua", countryCode: "NI" },
  "NL": { commonName: "Netherlands", fullName: "Netherlands (Kingdom of the)", countryCode: "NL" },
  "NO": { commonName: "Norway", fullName: "Norway", countryCode: "NO" },
  "NP": { commonName: "Nepal", fullName: "Nepal", countryCode: "NP" },
  "NR": { commonName: "Nauru", fullName: "Nauru (Republic of)", countryCode: "NR" },
  "NU": { commonName: "Niue", fullName: "Niue", countryCode: "NU" },
  "NZ": { commonName: "New Zealand", fullName: "New Zealand", countryCode: "NZ" },
  "OM": { commonName: "Oman", fullName: "Oman (Sultanate of)", countryCode: "OM" },
  "PA": { commonName: "Panama", fullName: "Panama (Republic of)", countryCode: "PA" },
  "PE": { commonName: "Peru", fullName: "Peru", countryCode: "PE" },
  "PF": { commonName: "French Polynesia", fullName: "French Polynesia", countryCode: "PF" },
  "PG": { commonName: "Papua New Guinea", fullName: "Papua New Guinea", countryCode: "PG" },
  "PH": { commonName: "Philippines", fullName: "Philippines (Republic of the)", countryCode: "PH" },
  "PK": { commonName: "Pakistan", fullName: "Pakistan (Islamic Republic of)", countryCode: "PK" },
  "PL": { commonName: "Poland", fullName: "Poland (Republic of)", countryCode: "PL" },
  "PM": { commonName: "Saint Pierre and Miquelon", fullName: "Saint Pierre and Miquelon (Territorial Collectivity of)", countryCode: "PM" },
  "PN": { commonName: "Pitcairn Island", fullName: "Pitcairn Island", countryCode: "PN" },
  "PR": { commonName: "Puerto Rico", fullName: "Puerto Rico", countryCode: "PR" },
  "PS": { commonName: "Palestinian Authority", fullName: "Palestinian Authority (based on Resolution 99 of PP-98)", countryCode: "PS" },
  "PT": { commonName: "Portugal", fullName: "Portugal", countryCode: "PT" },
  "PT-20": { commonName: "Azores", fullName: "Azores (Portuguese isles of)", countryCode: "PT-20" },
  "PT-30": { commonName: "Madeira", fullName: "Madeira (Portuguese isles of)", countryCode: "PT-30" },
  "PW": { commonName: "Palau", fullName: "Palau (Republic of)", countryCode: "PW" },
  "PY": { commonName: "Paraguay", fullName: "Paraguay (Republic of)", countryCode: "PY" },
  "QA": { commonName: "Qatar", fullName: "Qatar (State of)", countryCode: "QA" },
  "RE": { commonName: "Réunion", fullName: "Réunion (French Department of)", countryCode: "RE" },
  "RO": { commonName: "Romania", fullName: "Romania", countryCode: "RO" },
  "RS": { commonName: "Serbia", fullName: "Serbia", countryCode: "RS" },
  "RU": { commonName: "Russian Federation", fullName: "Russian Federation", countryCode: "RU" },
  "RW": { commonName: "Rwandese Republic", fullName: "Rwandese Republic", countryCode: "RW" },
  "SA": { commonName: "Saudi Arabia", fullName: "Saudi Arabia (Kingdom of)", countryCode: "SA" },
  "SB": { commonName: "Solomon Islands", fullName: "Solomon Islands", countryCode: "SB" },
  "SC": { commonName: "Seychelles", fullName: "Seychelles (Republic of)", countryCode: "SC" },
  "SD": { commonName: "Sudan", fullName: "Sudan (Republic of the)", countryCode: "SD" },
  "SE": { commonName: "Sweden", fullName: "Sweden", countryCode: "SE" },
  "SG": { commonName: "Singapore", fullName: "Singapore (Republic of)", countryCode: "SG" },
  "SH-AC": { commonName: "Ascension Island", fullName: "Ascension Island", countryCode: "SH-AC" },
  "SH-HL": { commonName: "Saint Helena", fullName: "Saint Helena", countryCode: "SH-HL" },
  "SI": { commonName: "Slovenia", fullName: "Slovenia (Republic of)", countryCode: "SI" },
  "SK": { commonName: "Slovakia", fullName: "Slovakia", countryCode: "SK" },
  "SL": { commonName: "Sierra Leone", fullName: "Sierra Leone", countryCode: "SL" },
  "SM": { commonName: "San Marino", fullName: "San Marino (Republic of)", countryCode: "SM" },
  "SN": { commonName: "Senegal", fullName: "Senegal (Republic of)", countryCode: "SN" },
  "SO": { commonName: "Somalia", fullName: "Somalia", countryCode: "SO" },
  "SR": { commonName: "Suriname", fullName: "Suriname (Republic of)", countryCode: "SR" },
  "SS": { commonName: "South Sudan", fullName: "South Sudan (Republic of the)", countryCode: "SS" },
  "ST": { commonName: "São Tomé and Príncipe", fullName: "São Tomé and Príncipe (Democratic Republic of)", countryCode: "ST" },
  "SV": { commonName: "El Salvador", fullName: "El Salvador (Republic of)", countryCode: "SV" },
  "SY": { commonName: "Syrian Arab Republic", fullName: "Syrian Arab Republic", countryCode: "SY" },
  "SZ": { commonName: "Swaziland", fullName: "Swaziland (Kingdom of)", countryCode: "SZ" },
  "TC": { commonName: "Turks and Caicos Islands", fullName: "Turks and Caicos Islands", countryCode: "TC" },
  "TD": { commonName: "Chad", fullName: "Chad (Republic of)", countryCode: "TD" },
  "TF": { commonName: "Adelie Land", fullName: "Adelie Land (French Southern Territories)", countryCode: "TF" },
  "TF-CA": { commonName: "Crozet Archipelago", fullName: "Crozet Archipelago", countryCode: "TF-CA" },
  "TF-KI": { commonName: "Kerguelen Islands", fullName: "Kerguelen Islands", countryCode: "TF-KI" },
  "TF-SP": { commonName: "Saint Paul and Amsterdam Islands", fullName: "Saint Paul and Amsterdam Islands", countryCode: "TF-SP" },
  "TG": { commonName: "Togolese Republic", fullName: "Togolese Republic", countryCode: "TG" },
  "TH": { commonName: "Thailand", fullName: "Thailand", countryCode: "TH" },
  "TJ": { commonName: "Tajikistan", fullName: "Tajikistan (Republic of)", countryCode: "TJ" },
  "TM": { commonName: "Turkmenistan", fullName: "Turkmenistan", countryCode: "TM" },
  "TN": { commonName: "Tunisia", fullName: "Tunisia", countryCode: "TN" },
  "TO": { commonName: "Tonga", fullName: "Tonga (Kingdom of)", countryCode: "TO" },
  "TR": { commonName: "Turkey", fullName: "Turkey", countryCode: "TR" },
  "TT": { commonName: "Trinidad and Tobago", fullName: "Trinidad and Tobago", countryCode: "TT" },
  "TV": { commonName: "Tuvalu", fullName: "Tuvalu", countryCode: "TV" },
  "TW": { commonName: "Taiwan", fullName: "Taiwan (Republic of China)", countryCode: "TW" },
  "TZ": { commonName: "Tanzania", fullName: "Tanzania (United Republic of)", countryCode: "TZ" },
  "UA": { commonName: "Ukraine", fullName: "Ukraine", countryCode: "UA" },
  "UG": { commonName: "Uganda", fullName: "Uganda (Republic of)", countryCode: "UG" },
  "US": { commonName: "United States of America", fullName: "United States of America", countryCode: "US" },
  "US-AK": { commonName: "Alaska", fullName: "Alaska (State of)", countryCode: "US-AK" },
  "UY": { commonName: "Uruguay", fullName: "Uruguay (Eastern Republic of)", countryCode: "UY" },
  "UZ": { commonName: "Uzbekistan", fullName: "Uzbekistan", countryCode: "UZ" },
  "VA": { commonName: "Vatican City State", fullName: "Vatican City State", countryCode: "VA" },
  "VC": { commonName: "Saint Vincent and the Grenadines", fullName: "Saint Vincent and the Grenadines", countryCode: "VC" },
  "VE": { commonName: "Venezuela", fullName: "Venezuela (Bolivarian Republic of)", countryCode: "VE" },
  "VG": { commonName: "British Virgin Islands", fullName: "British Virgin Islands", countryCode: "VG" },
  "VI": { commonName: "United States Virgin Islands", fullName: "United States Virgin Islands", countryCode: "VI" },
  "VN": { commonName: "Vietnam", fullName: "Vietnam (Socialist Republic of)", countryCode: "VN" },
  "VU": { commonName: "Vanuatu", fullName: "Vanuatu (Republic of)", countryCode: "VU" },
  "WF": { commonName: "Wallis and Futuna Islands", fullName: "Wallis and Futuna Islands", countryCode: "WF" },
  "WS": { commonName: "Samoa", fullName: "Samoa (Independent State of)", countryCode: "WS" },
  "YE": { commonName: "Yemen", fullName: "Yemen (Republic of)", countryCode: "YE" },
  "ZA": { commonName: "South Africa", fullName: "South Africa (Republic of)", countryCode: "ZA" },
  "ZM": { commonName: "Zambia", fullName: "Zambia (Republic of)", countryCode: "ZM" },
  "ZW": { commonName: "Zimbabwe", fullName: "Zimbabwe (Republic of)", countryCode: "ZW" },
}

const midCountryCodes: { [mid: string]: string } = {
  "201": "AL",
  "202": "AD",
  "203": "AT",
  "204": "PT-20",
  "205": "BE",
  "206": "BY",
  "207": "BG",
  "208": "VA",
  "209": "CY",
  "210": "CY",
  "212": "CY",
  "211": "DE",
  "218": "DE",
  "213": "GE",
  "214": "MD",
  "215": "MT",
  "229": "MT",
  "248": "MT",
  "249": "MT",
  "256": "MT",
  "216": "AM",
  "219": "DK",
  "220": "DK",
  "224": "ES",
  "225": "ES",
  "226": "FR",
  "227": "FR",
  "228": "FR",
  "230": "FI",
  "231": "FO",
  "232": "GB",
  "233": "GB",
  "234": "GB",
  "235": "GB",
  "236": "GI",
  "237": "GR",
  "239": "GR",
  "240": "GR",
  "241": "GR",
  "238": "HR",
  "242": "MA",
  "243": "HU",
  "244": "NL",
  "245": "NL",
  "246": "NL",
  "247": "IT",
  "250": "IE",
  "251": "IS",
  "252": "LI",
  "253": "LU",
  "254": "MC",
  "255": "PT-30",
  "257": "NO",
  "258": "NO",
  "259": "NO",
  "261": "PL",
  "262": "ME",
  "263": "PT",
  "264": "RO",
  "265": "SE",
  "266": "SE",
  "267": "SK",
  "268": "SM",
  "269": "CH",
  "270": "CZ",
  "271": "TR",
  "272": "UA",
  "273": "RU",
  "274": "MK",
  "275": "LV",
  "276": "EE",
  "277": "LT",
  "278": "SI",
  "279": "RS",
  "301": "AI",
  "303": "US-AK",
  "304": "AG",
  "305": "AG",
  "306": "BQ,CW,SX",
  "307": "AW",
  "308": "BS",
  "309": "BS",
  "311": "BS",
  "310": "BM",
  "312": "BZ",
  "314": "BB",
  "316": "CA",
  "319": "KY",
  "321": "CR",
  "323": "CU",
  "325": "DM",
  "327": "DO",
  "329": "GP",
  "330": "GD",
  "331": "GL",
  "332": "GT",
  "334": "HN",
  "336": "HT",
  "338": "US",
  "366": "US",
  "367": "US",
  "368": "US",
  "369": "US",
  "339": "JM",
  "341": "KN",
  "343": "LC",
  "345": "MX",
  "347": "MQ",
  "348": "MS",
  "350": "NI",
  "351": "PA",
  "352": "PA",
  "353": "PA",
  "354": "PA",
  "355": "PA",
  "356": "PA",
  "357": "PA",
  "370": "PA",
  "371": "PA",
  "372": "PA",
  "373": "PA",
  "374": "PA",
  "358": "PR",
  "359": "SV",
  "361": "PM",
  "362": "TT",
  "364": "TC",
  "375": "VC",
  "376": "VC",
  "377": "VC",
  "378": "VG",
  "379": "VI",
  "401": "AF",
  "403": "SA",
  "405": "BD",
  "408": "BH",
  "410": "BT",
  "412": "CN",
  "413": "CN",
  "414": "CN",
  "416": "TW",
  "417": "LK",
  "419": "IN",
  "422": "IR",
  "423": "AZ",
  "425": "IQ",
  "428": "IL",
  "431": "JP",
  "432": "JP",
  "434": "TM",
  "436": "KZ",
  "437": "UZ",
  "438": "JO",
  "440": "KR",
  "441": "KR",
  "443": "PS",
  "445": "KP",
  "447": "KW",
  "450": "LB",
  "451": "KG",
  "453": "MO",
  "455": "MV",
  "457": "MN",
  "459": "NP",
  "461": "OM",
  "463": "PK",
  "466": "QA",
  "468": "SY",
  "470": "AE",
  "471": "AE",
  "472": "TJ",
  "473": "YE",
  "475": "YE",
  "477": "HK",
  "478": "BA",
  "501": "TF",
  "503": "AU",
  "506": "MM",
  "508": "BN",
  "510": "FM",
  "511": "PW",
  "512": "NZ",
  "514": "KH",
  "515": "KH",
  "516": "CX",
  "518": "CK",
  "520": "FJ",
  "523": "CC",
  "525": "ID",
  "529": "KI",
  "531": "LA",
  "533": "MY",
  "536": "MP",
  "538": "MH",
  "540": "NC",
  "542": "NU",
  "544": "NR",
  "546": "PF",
  "548": "PH",
  "553": "PG",
  "555": "PN",
  "557": "SB",
  "559": "AS",
  "561": "WS",
  "563": "SG",
  "564": "SG",
  "565": "SG",
  "566": "SG",
  "567": "TH",
  "570": "TO",
  "572": "TV",
  "574": "VN",
  "576": "VU",
  "577": "VU",
  "578": "WF",
  "601": "ZA",
  "603": "AO",
  "605": "DZ",
  "607": "TF-SP",
  "608": "SH-AC",
  "609": "BI",
  "610": "BJ",
  "611": "BW",
  "612": "CF",
  "613": "CM",
  "615": "CG",
  "616": "KM",
  "620": "KM",
  "617": "CV",
  "618": "TF-CA",
  "619": "CI",
  "621": "DJ",
  "622": "EG",
  "624": "ET",
  "625": "ER",
  "626": "GA",
  "627": "GH",
  "629": "GM",
  "630": "GW",
  "631": "GQ",
  "632": "GN",
  "633": "BF",
  "634": "KE",
  "635": "TF-KI",
  "636": "LR",
  "637": "LR",
  "638": "SS",
  "642": "LY",
  "644": "LS",
  "645": "MU",
  "647": "MG",
  "649": "ML",
  "650": "MZ",
  "654": "MR",
  "655": "MW",
  "656": "NE",
  "657": "NG",
  "659": "NA",
  "660": "RE",
  "661": "RW",
  "662": "SD",
  "663": "SN",
  "664": "SC",
  "665": "SH-HL",
  "666": "SO",
  "667": "SL",
  "668": "ST",
  "669": "SZ",
  "670": "TD",
  "671": "TG",
  "672": "TN",
  "674": "TZ",
  "677": "TZ",
  "675": "UG",
  "676": "CD",
  "678": "ZM",
  "679": "ZW",
  "701": "AR",
  "710": "BR",
  "720": "BO",
  "725": "CL",
  "730": "CO",
  "735": "EC",
  "740": "FK",
  "745": "GF",
  "750": "GY",
  "755": "PY",
  "760": "PE",
  "765": "SR",
  "770": "UY",
  "775": "VE",
};