export interface MMSICountry {
  fullName: string;
  commonName: string;
  code: string;
}

export const midCountries: { [mid: number]: MMSICountry } = {
  201: { commonName: 'Albania', fullName: 'Albania (Republic of)', code: 'AL' },
  202: { commonName: 'Andorra', fullName: 'Andorra (Principality of)', code: '' },
  203: { commonName: 'Austria', fullName: 'Austria', code: '' },
  204: { commonName: 'Azores', fullName: 'Azores (Portuguese isles of)', code: '' },
  205: { commonName: 'Belgium', fullName: 'Belgium', code: '' },
  206: { commonName: 'Belarus', fullName: 'Belarus (Republic of)', code: '' },
  207: { commonName: 'Bulgaria', fullName: 'Bulgaria (Republic of)', code: '' },
  208: { commonName: 'Vatican City State', fullName: 'Vatican City State', code: '' },
  209: { commonName: 'Cyprus', fullName: 'Cyprus (Republic of)', code: '' },
  210: { commonName: 'Cyprus', fullName: 'Cyprus (Republic of)', code: '' },
  212: { commonName: 'Cyprus', fullName: 'Cyprus (Republic of)', code: '' },
  211: { commonName: 'Germany', fullName: 'Germany (Federal Republic of)', code: '' },
  218: { commonName: 'Germany', fullName: 'Germany (Federal Republic of)', code: '' },
  213: { commonName: 'Georgia', fullName: 'Georgia', code: '' },
  214: { commonName: 'Moldova', fullName: 'Moldova (Republic of)', code: '' },
  215: { commonName: 'Malta', fullName: 'Malta', code: '' },
  229: { commonName: 'Malta', fullName: 'Malta', code: '' },
  248: { commonName: 'Malta', fullName: 'Malta', code: '' },
  249: { commonName: 'Malta', fullName: 'Malta', code: '' },
  256: { commonName: 'Malta', fullName: 'Malta', code: '' },
  216: { commonName: 'Armenia', fullName: 'Armenia (Republic of)', code: '' },
  219: { commonName: 'Denmark', fullName: 'Denmark', code: '' },
  220: { commonName: 'Denmark', fullName: 'Denmark', code: '' },
  224: { commonName: 'Spain', fullName: 'Spain', code: '' },
  225: { commonName: 'Spain', fullName: 'Spain', code: '' },
  226: { commonName: 'France', fullName: 'France', code: '' },
  227: { commonName: 'France', fullName: 'France', code: '' },
  228: { commonName: 'France', fullName: 'France', code: '' },
  230: { commonName: 'Finland', fullName: 'Finland', code: '' },
  231: { commonName: 'Faroe Islands', fullName: 'Faroe Islands', code: '' },
  232: { commonName: 'United Kingdom', fullName: 'United Kingdom of Great Britain and Northern Ireland', code: '' },
  233: { commonName: 'United Kingdom', fullName: 'United Kingdom of Great Britain and Northern Ireland', code: '' },
  234: { commonName: 'United Kingdom', fullName: 'United Kingdom of Great Britain and Northern Ireland', code: '' },
  235: { commonName: 'United Kingdom', fullName: 'United Kingdom of Great Britain and Northern Ireland', code: '' },
  236: { commonName: 'Gibraltar', fullName: 'Gibraltar', code: '' },
  237: { commonName: 'Greece', fullName: 'Greece', code: '' },
  239: { commonName: 'Greece', fullName: 'Greece', code: '' },
  240: { commonName: 'Greece', fullName: 'Greece', code: '' },
  241: { commonName: 'Greece', fullName: 'Greece', code: '' },
  238: { commonName: 'Croatia', fullName: 'Croatia (Republic of)', code: '' },
  242: { commonName: 'Morocco', fullName: 'Morocco (Kingdom of)', code: '' },
  243: { commonName: 'Hungary', fullName: 'Hungary (Republic of)', code: '' },
  244: { commonName: 'Netherlands', fullName: 'Netherlands (Kingdom of the)', code: '' },
  245: { commonName: 'Netherlands', fullName: 'Netherlands (Kingdom of the)', code: '' },
  246: { commonName: 'Netherlands', fullName: 'Netherlands (Kingdom of the)', code: '' },
  247: { commonName: 'Italy', fullName: 'Italy', code: '' },
  250: { commonName: 'Ireland', fullName: 'Ireland', code: '' },
  251: { commonName: 'Iceland', fullName: 'Iceland', code: '' },
  252: { commonName: 'Liechtenstein', fullName: 'Liechtenstein (Principality of)', code: '' },
  253: { commonName: 'Luxembourg', fullName: 'Luxembourg', code: '' },
  254: { commonName: 'Monaco', fullName: 'Monaco (Principality of)', code: '' },
  255: { commonName: 'Madeira', fullName: 'Madeira (Portuguese isles of)', code: '' },
  257: { commonName: 'Norway', fullName: 'Norway', code: '' },
  258: { commonName: 'Norway', fullName: 'Norway', code: '' },
  259: { commonName: 'Norway', fullName: 'Norway', code: '' },
  261: { commonName: 'Poland', fullName: 'Poland (Republic of)', code: '' },
  262: { commonName: 'Montenegro', fullName: 'Montenegro (Republic of)', code: '' },
  263: { commonName: 'Portugal', fullName: 'Portugal', code: '' },
  264: { commonName: 'Romania', fullName: 'Romania', code: '' },
  265: { commonName: 'Sweden', fullName: 'Sweden', code: '' },
  266: { commonName: 'Sweden', fullName: 'Sweden', code: '' },
  267: { commonName: 'Slovakia', fullName: 'Slovakia', code: '' },
  268: { commonName: 'San Marino', fullName: 'San Marino (Republic of)', code: '' },
  269: { commonName: 'Switzerland', fullName: 'Switzerland (Confederation of)', code: '' },
  270: { commonName: 'Czech Republic', fullName: 'Czech Republic', code: '' },
  271: { commonName: 'Turkey', fullName: 'Turkey', code: '' },
  272: { commonName: 'Ukraine', fullName: 'Ukraine', code: '' },
  273: { commonName: 'Russian Federation', fullName: 'Russian Federation', code: '' },
  274: { commonName: 'Macedonia', fullName: 'Macedonia', code: '' },
  275: { commonName: 'Latvia', fullName: 'Latvia (Republic of)', code: '' },
  276: { commonName: 'Estonia', fullName: 'Estonia (Republic of)', code: '' },
  277: { commonName: 'Lithuania', fullName: 'Lithuania (Republic of)', code: '' },
  278: { commonName: 'Slovenia', fullName: 'Slovenia (Republic of)', code: '' },
  279: { commonName: 'Serbia', fullName: 'Serbia', code: '' },
  301: { commonName: 'Anguilla', fullName: 'Anguilla', code: '' },
  303: { commonName: 'Alaska', fullName: 'Alaska (State of)', code: '' },
  304: { commonName: 'Antigua and Barbuda', fullName: 'Antigua and Barbuda', code: '' },
  305: { commonName: 'Antigua and Barbuda', fullName: 'Antigua and Barbuda', code: '' },
  306: { commonName: 'Bonaire, Sint Eustatius and Saba - Netherlands', fullName: 'Bonaire, Sint Eustatius and Saba - Netherlands (Kingdom of the)', code: '' },
  306: { commonName: 'Curaçao - Netherlands', fullName: 'Curaçao - Netherlands (Kingdom of the)', code: '' },
  306: { commonName: 'Sint Maarten', fullName: 'Sint Maarten (Dutch part)', code: '' },
  307: { commonName: 'Aruba', fullName: 'Aruba', code: '' },
  308: { commonName: 'Bahamas', fullName: 'Bahamas (Commonwealth of the)', code: '' },
  309: { commonName: 'Bahamas', fullName: 'Bahamas (Commonwealth of the)', code: '' },
  311: { commonName: 'Bahamas', fullName: 'Bahamas (Commonwealth of the)', code: '' },
  310: { commonName: 'Bermuda', fullName: 'Bermuda', code: '' },
  312: { commonName: 'Belize', fullName: 'Belize', code: '' },
  314: { commonName: 'Barbados', fullName: 'Barbados', code: '' },
  316: { commonName: 'Canada', fullName: 'Canada', code: '' },
  319: { commonName: 'Cayman Islands', fullName: 'Cayman Islands', code: '' },
  321: { commonName: 'Costa Rica', fullName: 'Costa Rica', code: '' },
  323: { commonName: 'Cuba', fullName: 'Cuba', code: '' },
  325: { commonName: 'Dominica', fullName: 'Dominica (Commonwealth of)', code: '' },
  327: { commonName: 'Dominican Republic', fullName: 'Dominican Republic', code: '' },
  329: { commonName: 'Guadeloupe', fullName: 'Guadeloupe (French Department of)', code: '' },
  330: { commonName: 'Grenada', fullName: 'Grenada', code: '' },
  331: { commonName: 'Greenland', fullName: 'Greenland', code: '' },
  332: { commonName: 'Guatemala', fullName: 'Guatemala (Republic of)', code: '' },
  334: { commonName: 'Honduras', fullName: 'Honduras (Republic of)', code: '' },
  336: { commonName: 'Haiti', fullName: 'Haiti (Republic of)', code: '' },
  338: { commonName: 'United States of America', fullName: 'United States of America', code: '' },
  366: { commonName: 'United States of America', fullName: 'United States of America', code: '' },
  367: { commonName: 'United States of America', fullName: 'United States of America', code: '' },
  368: { commonName: 'United States of America', fullName: 'United States of America', code: '' },
  369: { commonName: 'United States of America', fullName: 'United States of America', code: '' },
  339: { commonName: 'Jamaica', fullName: 'Jamaica', code: '' },
  341: { commonName: 'Saint Kitts and Nevis', fullName: 'Saint Kitts and Nevis', code: '' },
  343: { commonName: 'Saint Lucia', fullName: 'Saint Lucia', code: '' },
  345: { commonName: 'Mexico', fullName: 'Mexico', code: '' },
  347: { commonName: 'Martinique', fullName: 'Martinique (French Department of)', code: '' },
  348: { commonName: 'Montserrat', fullName: 'Montserrat', code: '' },
  350: { commonName: 'Nicaragua', fullName: 'Nicaragua', code: '' },
  351: { commonName: 'Panama', fullName: 'Panama (Republic of)', code: '' },
  352: { commonName: 'Panama', fullName: 'Panama (Republic of)', code: '' },
  353: { commonName: 'Panama', fullName: 'Panama (Republic of)', code: '' },
  354: { commonName: 'Panama', fullName: 'Panama (Republic of)', code: '' },
  355: { commonName: 'Panama', fullName: 'Panama (Republic of)', code: '' },
  356: { commonName: 'Panama', fullName: 'Panama (Republic of)', code: '' },
  357: { commonName: 'Panama', fullName: 'Panama (Republic of)', code: '' },
  370: { commonName: 'Panama', fullName: 'Panama (Republic of)', code: '' },
  371: { commonName: 'Panama', fullName: 'Panama (Republic of)', code: '' },
  372: { commonName: 'Panama', fullName: 'Panama (Republic of)', code: '' },
  373: { commonName: 'Panama', fullName: 'Panama (Republic of)', code: '' },
  374: { commonName: 'Panama', fullName: 'Panama (Republic of)', code: '' },
  358: { commonName: 'Puerto Rico', fullName: 'Puerto Rico', code: '' },
  359: { commonName: 'El Salvador', fullName: 'El Salvador (Republic of)', code: '' },
  361: { commonName: 'Saint Pierre and Miquelon', fullName: 'Saint Pierre and Miquelon (Territorial Collectivity of)', code: '' },
  362: { commonName: 'Trinidad and Tobago', fullName: 'Trinidad and Tobago', code: '' },
  364: { commonName: 'Turks and Caicos Islands', fullName: 'Turks and Caicos Islands', code: '' },
  375: { commonName: 'Saint Vincent and the Grenadines', fullName: 'Saint Vincent and the Grenadines', code: '' },
  376: { commonName: 'Saint Vincent and the Grenadines', fullName: 'Saint Vincent and the Grenadines', code: '' },
  377: { commonName: 'Saint Vincent and the Grenadines', fullName: 'Saint Vincent and the Grenadines', code: '' },
  378: { commonName: 'British Virgin Islands', fullName: 'British Virgin Islands', code: '' },
  379: { commonName: 'United States Virgin Islands', fullName: 'United States Virgin Islands', code: '' },
  401: { commonName: 'Afghanistan', fullName: 'Afghanistan', code: '' },
  403: { commonName: 'Saudi Arabia', fullName: 'Saudi Arabia (Kingdom of)', code: '' },
  405: { commonName: 'Bangladesh', fullName: 'Bangladesh (People\'s Republic of)', code: '' },
  408: { commonName: 'Bahrain', fullName: 'Bahrain (Kingdom of)', code: '' },
  410: { commonName: 'Bhutan', fullName: 'Bhutan (Kingdom of)', code: '' },
  412: { commonName: 'China', fullName: 'China (People\'s Republic of)', code: '' },
  413: { commonName: 'China', fullName: 'China (People\'s Republic of)', code: '' },
  414: { commonName: 'China', fullName: 'China (People\'s Republic of)', code: '' },
  416: { commonName: 'Taiwan', fullName: 'Taiwan (Republic of China)', code: '' },
  417: { commonName: 'Sri Lanka', fullName: 'Sri Lanka (Democratic Socialist Republic of)', code: '' },
  419: { commonName: 'India', fullName: 'India (Republic of)', code: '' },
  422: { commonName: 'Iran', fullName: 'Iran (Islamic Republic of)', code: '' },
  423: { commonName: 'Azerbaijani Republic', fullName: 'Azerbaijani Republic', code: '' },
  425: { commonName: 'Iraq', fullName: 'Iraq (Republic of)', code: '' },
  428: { commonName: 'Israel', fullName: 'Israel (State of)', code: '' },
  431: { commonName: 'Japan', fullName: 'Japan', code: '' },
  432: { commonName: 'Japan', fullName: 'Japan', code: '' },
  434: { commonName: 'Turkmenistan', fullName: 'Turkmenistan', code: '' },
  436: { commonName: 'Kazakhstan', fullName: 'Kazakhstan (Republic of)', code: '' },
  437: { commonName: 'Uzbekistan', fullName: 'Uzbekistan', code: '' },
  438: { commonName: 'Jordan', fullName: 'Jordan (Hashemite Kingdom of)', code: '' },
  440: { commonName: 'Korea', fullName: 'Korea (Republic of)', code: '' },
  441: { commonName: 'Korea', fullName: 'Korea (Republic of)', code: '' },
  443: { commonName: 'Palestinian Authority', fullName: 'Palestinian Authority (based on Resolution 99 of PP-98)', code: '' },
  445: { commonName: 'North Korea', fullName: 'North Korea', code: '' },
  447: { commonName: 'Kuwait', fullName: 'Kuwait (State of)', code: '' },
  450: { commonName: 'Lebanon', fullName: 'Lebanon', code: '' },
  451: { commonName: 'Kyrgyzstan', fullName: 'Kyrgyzstan', code: '' },
  453: { commonName: 'Macao', fullName: 'Macao', code: '' },
  455: { commonName: 'Maldives', fullName: 'Maldives (Republic of)', code: '' },
  457: { commonName: 'Mongolia', fullName: 'Mongolia', code: '' },
  459: { commonName: 'Nepal', fullName: 'Nepal', code: '' },
  461: { commonName: 'Oman', fullName: 'Oman (Sultanate of)', code: '' },
  463: { commonName: 'Pakistan', fullName: 'Pakistan (Islamic Republic of)', code: '' },
  466: { commonName: 'Qatar', fullName: 'Qatar (State of)', code: '' },
  468: { commonName: 'Syrian Arab Republic', fullName: 'Syrian Arab Republic', code: '' },
  470: { commonName: 'United Arab Emirates', fullName: 'United Arab Emirates', code: '' },
  471: { commonName: 'United Arab Emirates', fullName: 'United Arab Emirates', code: '' },
  472: { commonName: 'Tajikistan', fullName: 'Tajikistan (Republic of)', code: '' },
  473: { commonName: 'Yemen', fullName: 'Yemen (Republic of)', code: '' },
  475: { commonName: 'Yemen', fullName: 'Yemen (Republic of)', code: '' },
  477: { commonName: 'Hong Kong', fullName: 'Hong Kong (Special Administrative Region of China)', code: '' },
  478: { commonName: 'Bosnia and Herzegovina', fullName: 'Bosnia and Herzegovina', code: '' },
  501: { commonName: 'Adelie Land', fullName: 'Adelie Land (French Southern Territories)', code: '' },
  503: { commonName: 'Australia', fullName: 'Australia', code: '' },
  506: { commonName: 'Myanmar', fullName: 'Myanmar (Union of)', code: '' },
  508: { commonName: 'Brunei Darussalam', fullName: 'Brunei Darussalam', code: '' },
  510: { commonName: 'Micronesia', fullName: 'Micronesia (Federated States of)', code: '' },
  511: { commonName: 'Palau', fullName: 'Palau (Republic of)', code: '' },
  512: { commonName: 'New Zealand', fullName: 'New Zealand', code: '' },
  514: { commonName: 'Cambodia', fullName: 'Cambodia (Kingdom of)', code: '' },
  515: { commonName: 'Cambodia', fullName: 'Cambodia (Kingdom of)', code: '' },
  516: { commonName: 'Christmas Island', fullName: 'Christmas Island (Indian Ocean)', code: '' },
  518: { commonName: 'Cook Islands', fullName: 'Cook Islands', code: '' },
  520: { commonName: 'Fiji', fullName: 'Fiji (Republic of)', code: '' },
  523: { commonName: 'Cocos', fullName: 'Cocos (Keeling) Islands', code: '' },
  525: { commonName: 'Indonesia', fullName: 'Indonesia (Republic of)', code: '' },
  529: { commonName: 'Kiribati', fullName: 'Kiribati (Republic of)', code: '' },
  531: { commonName: 'Lao People\'s Democratic Republic', fullName: 'Lao People\'s Democratic Republic (Laos)', code: '' },
  533: { commonName: 'Malaysia', fullName: 'Malaysia', code: '' },
  536: { commonName: 'Northern Mariana Islands', fullName: 'Northern Mariana Islands (Commonwealth of the)', code: '' },
  538: { commonName: 'Marshall Islands', fullName: 'Marshall Islands (Republic of the)', code: '' },
  540: { commonName: 'New Caledonia', fullName: 'New Caledonia', code: '' },
  542: { commonName: 'Niue', fullName: 'Niue', code: '' },
  544: { commonName: 'Nauru', fullName: 'Nauru (Republic of)', code: '' },
  546: { commonName: 'French Polynesia', fullName: 'French Polynesia', code: '' },
  548: { commonName: 'Philippines', fullName: 'Philippines (Republic of the)', code: '' },
  553: { commonName: 'Papua New Guinea', fullName: 'Papua New Guinea', code: '' },
  555: { commonName: 'Pitcairn Island', fullName: 'Pitcairn Island', code: '' },
  557: { commonName: 'Solomon Islands', fullName: 'Solomon Islands', code: '' },
  559: { commonName: 'American Samoa', fullName: 'American Samoa', code: '' },
  561: { commonName: 'Samoa', fullName: 'Samoa (Independent State of)', code: '' },
  563: { commonName: 'Singapore', fullName: 'Singapore (Republic of)', code: '' },
  564: { commonName: 'Singapore', fullName: 'Singapore (Republic of)', code: '' },
  565: { commonName: 'Singapore', fullName: 'Singapore (Republic of)', code: '' },
  566: { commonName: 'Singapore', fullName: 'Singapore (Republic of)', code: '' },
  567: { commonName: 'Thailand', fullName: 'Thailand', code: '' },
  570: { commonName: 'Tonga', fullName: 'Tonga (Kingdom of)', code: '' },
  572: { commonName: 'Tuvalu', fullName: 'Tuvalu', code: '' },
  574: { commonName: 'Vietnam', fullName: 'Vietnam (Socialist Republic of)', code: '' },
  576: { commonName: 'Vanuatu', fullName: 'Vanuatu (Republic of)', code: '' },
  577: { commonName: 'Vanuatu', fullName: 'Vanuatu (Republic of)', code: '' },
  578: { commonName: 'Wallis and Futuna Islands', fullName: 'Wallis and Futuna Islands', code: '' },
  601: { commonName: 'South Africa', fullName: 'South Africa (Republic of)', code: '' },
  603: { commonName: 'Angola', fullName: 'Angola (Republic of)', code: '' },
  605: { commonName: 'Algeria', fullName: 'Algeria (People\'s Democratic Republic of)', code: '' },
  607: { commonName: 'Saint Paul and Amsterdam Islands', fullName: 'Saint Paul and Amsterdam Islands', code: '' },
  608: { commonName: 'Ascension Island', fullName: 'Ascension Island', code: '' },
  609: { commonName: 'Burundi', fullName: 'Burundi (Republic of)', code: '' },
  610: { commonName: 'Benin', fullName: 'Benin (Republic of)', code: '' },
  611: { commonName: 'Botswana', fullName: 'Botswana (Republic of)', code: '' },
  612: { commonName: 'Central African Republic', fullName: 'Central African Republic', code: '' },
  613: { commonName: 'Cameroon', fullName: 'Cameroon (Republic of)', code: '' },
  615: { commonName: 'Congo', fullName: 'Congo (Republic of the)', code: '' },
  616: { commonName: 'Comoros', fullName: 'Comoros (Union of the)', code: '' },
  620: { commonName: 'Comoros', fullName: 'Comoros (Union of the)', code: '' },
  617: { commonName: 'Cape Verde', fullName: 'Cape Verde (Republic of)', code: '' },
  618: { commonName: 'Crozet Archipelago', fullName: 'Crozet Archipelago', code: '' },
  619: { commonName: 'Côte d\'Ivoire', fullName: 'Côte d\'Ivoire (Republic of)', code: '' },
  621: { commonName: 'Djibouti', fullName: 'Djibouti (Republic of)', code: '' },
  622: { commonName: 'Egypt', fullName: 'Egypt (Arab Republic of)', code: '' },
  624: { commonName: 'Ethiopia', fullName: 'Ethiopia (Federal Democratic Republic of)', code: '' },
  625: { commonName: 'Eritrea', fullName: 'Eritrea', code: '' },
  626: { commonName: 'Gabonese Republic', fullName: 'Gabonese Republic', code: '' },
  627: { commonName: 'Ghana', fullName: 'Ghana', code: '' },
  629: { commonName: 'Gambia', fullName: 'Gambia (Republic of the)', code: '' },
  630: { commonName: 'Guinea-Bissau', fullName: 'Guinea-Bissau (Republic of)', code: '' },
  631: { commonName: 'Equatorial Guinea', fullName: 'Equatorial Guinea (Republic of)', code: '' },
  632: { commonName: 'Guinea', fullName: 'Guinea (Republic of)', code: '' },
  633: { commonName: 'Burkina Faso', fullName: 'Burkina Faso', code: '' },
  634: { commonName: 'Kenya', fullName: 'Kenya (Republic of)', code: '' },
  635: { commonName: 'Kerguelen Islands', fullName: 'Kerguelen Islands', code: '' },
  636: { commonName: 'Liberia', fullName: 'Liberia (Republic of)', code: '' },
  637: { commonName: 'Liberia', fullName: 'Liberia (Republic of)', code: '' },
  638: { commonName: 'South Sudan', fullName: 'South Sudan (Republic of the)', code: '' },
  642: { commonName: 'Libya', fullName: 'Libya', code: '' },
  644: { commonName: 'Lesotho', fullName: 'Lesotho (Kingdom of)', code: '' },
  645: { commonName: 'Mauritius', fullName: 'Mauritius (Republic of)', code: '' },
  647: { commonName: 'Madagascar', fullName: 'Madagascar (Republic of)', code: '' },
  649: { commonName: 'Mali', fullName: 'Mali (Republic of)', code: '' },
  650: { commonName: 'Mozambique', fullName: 'Mozambique (Republic of)', code: '' },
  654: { commonName: 'Mauritania', fullName: 'Mauritania (Islamic Republic of)', code: '' },
  655: { commonName: 'Malawi', fullName: 'Malawi', code: '' },
  656: { commonName: 'Niger', fullName: 'Niger (Republic of the)', code: '' },
  657: { commonName: 'Nigeria', fullName: 'Nigeria (Federal Republic of)', code: '' },
  659: { commonName: 'Namibia', fullName: 'Namibia (Republic of)', code: '' },
  660: { commonName: 'Réunion', fullName: 'Réunion (French Department of)', code: '' },
  661: { commonName: 'Rwandese Republic', fullName: 'Rwandese Republic', code: '' },
  662: { commonName: 'Sudan', fullName: 'Sudan (Republic of the)', code: '' },
  663: { commonName: 'Senegal', fullName: 'Senegal (Republic of)', code: '' },
  664: { commonName: 'Seychelles', fullName: 'Seychelles (Republic of)', code: '' },
  665: { commonName: 'Saint Helena', fullName: 'Saint Helena', code: '' },
  666: { commonName: 'Somalia', fullName: 'Somalia', code: '' },
  667: { commonName: 'Sierra Leone', fullName: 'Sierra Leone', code: '' },
  668: { commonName: 'São Tomé and Príncipe', fullName: 'São Tomé and Príncipe (Democratic Republic of)', code: '' },
  669: { commonName: 'Swaziland', fullName: 'Swaziland (Kingdom of)', code: '' },
  670: { commonName: 'Chad', fullName: 'Chad (Republic of)', code: '' },
  671: { commonName: 'Togolese Republic', fullName: 'Togolese Republic', code: '' },
  672: { commonName: 'Tunisia', fullName: 'Tunisia', code: '' },
  674: { commonName: 'Tanzania', fullName: 'Tanzania (United Republic of)', code: '' },
  677: { commonName: 'Tanzania', fullName: 'Tanzania (United Republic of)', code: '' },
  675: { commonName: 'Uganda', fullName: 'Uganda (Republic of)', code: '' },
  676: { commonName: 'Democratic Republic of the Congo', fullName: 'Democratic Republic of the Congo', code: '' },
  678: { commonName: 'Zambia', fullName: 'Zambia (Republic of)', code: '' },
  679: { commonName: 'Zimbabwe', fullName: 'Zimbabwe (Republic of)', code: '' },
  701: { commonName: 'Argentine Republic', fullName: 'Argentine Republic', code: '' },
  710: { commonName: 'Brazil', fullName: 'Brazil (Federative Republic of)', code: '' },
  720: { commonName: 'Bolivia', fullName: 'Bolivia (Republic of)', code: '' },
  725: { commonName: 'Chile', fullName: 'Chile', code: '' },
  730: { commonName: 'Colombia', fullName: 'Colombia (Republic of)', code: '' },
  735: { commonName: 'Ecuador', fullName: 'Ecuador', code: '' },
  740: { commonName: 'Falkland Islands', fullName: 'Falkland Islands (Malvinas)', code: '' },
  745: { commonName: 'Guiana', fullName: 'Guiana (French Department of)', code: '' },
  750: { commonName: 'Guyana', fullName: 'Guyana', code: '' },
  755: { commonName: 'Paraguay', fullName: 'Paraguay (Republic of)', code: '' },
  760: { commonName: 'Peru', fullName: 'Peru', code: '' },
  765: { commonName: 'Suriname', fullName: 'Suriname (Republic of)', code: '' },
  770: { commonName: 'Uruguay', fullName: 'Uruguay (Eastern Republic of)', code: '' },
  775: { commonName: 'Venezuela', fullName: 'Venezuela (Bolivarian Republic of)',   code: '' },
};